version: '2'
services:

  kafka-4:
    image: confluentinc/cp-enterprise-kafka:latest
    ports:
      - "19082:19082"
    environment:
      KAFKA_BROKER_ID: 7
      KAFKA_ZOOKEEPER_CONNECT: 172.16.0.63:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.1.75:19082
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:19082
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 172.16.0.63:22181
    extra_hosts:
      - "moby:127.0.0.1"
    volumes:
      - ./kafka4/data:/var/lib/kafka/data

  kafka-5:
    image: confluentinc/cp-enterprise-kafka:latest
    ports:
      - "29082:29082"
    environment:
      KAFKA_BROKER_ID: 8
      KAFKA_ZOOKEEPER_CONNECT: 172.16.0.63:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.1.75:29082
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:29082
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 172.16.0.63:22181
    extra_hosts:
      - "moby:127.0.0.1"
    volumes:
      - ./kafka5/data:/var/lib/kafka/data

  kafka-6:
    image: confluentinc/cp-enterprise-kafka:latest
    ports:
      - "39082:39082"
    environment:
      KAFKA_BROKER_ID: 9
      KAFKA_ZOOKEEPER_CONNECT: 172.16.0.63:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.1.75:39082
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:39082
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 172.16.0.63:22181
    extra_hosts:
      - "moby:127.0.0.1"
    volumes:
      - ./kafka6/data:/var/lib/kafka/data   
